### ISSUE TITLE
None Data Exception

### ISSUE THREAD

**Issue by tiaradwiputri** [onlyphantom/pedagogy#2]
### NULL data on response

Got an error when logging in with iffa@algorit.ma, supposedly caused by **single_response.html** can't handle NULL exception. Some of the satisfaction_score was left blank on earlier survey.

### NULL data on workshop

Got an error when logging in with samuel@algorit.ma, supposedly caused by **analytics.py** can't handle NULL exception for class size in workshop table.

**Comment by onlyphantom** [comment]
The easiest fix I can think of for the second scenario is to set the fields to be `nullable=False`. This means the admin has to add a workshop hour, class size etc each time he/she creates a workshop. 

On the first issue: Nice catch! Wasn't aware of it earlier but will look into it

**Comment by tiaradwiputri** [comment]
Updating all NULL value in satisfaction score as 3 and venue score as 4 (average score received). All upcoming workshop should no longer has this issue since all workshop response is created through pedagogy apps and will have NULL restriction in submitting forms.
