### ISSUE TITLE
Caching leads to same results for different instructors

### ISSUE THREAD

**Issue by tiaradwiputri** [onlyphantom/pedagogy#37]
Login using two different instructors result in the same fetched data. (The latter account login still uses the last login data)

Logging in with another account can't access accomplishment page. It would redirect to index page.

The behavior might arose from last updates on caching, seems like it is maintaining a server cache from different login session.

**Comment by tiaradwiputri** [comment]
1. Restart application on Azure portal
2. Log in as tiara@algorit.ma
Displayed the following data:
![image](https://user-images.githubusercontent.com/8868527/56565781-5633f680-65db-11e9-926b-2c9411cf2b51.png)

3. Log in as ajeng@algorit.ma on different machine
Displayed the following data:
![image](https://user-images.githubusercontent.com/8868527/56565843-8085b400-65db-11e9-81ef-91ff6446f5c6.png)

Shows the exact same results in accomplishment page, on overall stats, comments, and workshops done

**Comment by onlyphantom** [comment]
Thank you for the quick response - it's a server side cache. Realised the error and pushed a fix. Now going to deploy. 

If it works in the production version (after deploy) I'll close the issue.
