### ISSUE TITLE
Update last_seen feature turn on again

### ISSUE THREAD

**Issue by onlyphantom** [onlyphantom/pedagogy#41]
One of the problem with sqlite (doesn't exist with Postgre) is its limitation when working with multiple IOs:

While the database connection is active, and we try to do an insertion, it throws an error:
> cursor.execute(statement, parameters) sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)

A quick fix on the sqlite incompatibility is to disable the write operation by turning off the last seen update feature:
```
def before_request():
    g.employee = None
    if current_user.is_authenticated:
        # current_user.last_seen = datetime.utcnow()
        g.employee = Employee.query.filter_by(email=current_user.email).first()
```

This problem is explained  on:  
- https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked/3172950
- https://stackoverflow.com/questions/32922210/why-does-a-query-invoke-a-auto-flush-in-sqlalchemy

1. Ideally, we want to check to see if production environment this should be enabled. 
2. Otherwise, we need to reconfigure sqlite a bit to allow non-blocking so that the features / functionalities for both dev and prod are exactly the same

**Comment by tiaradwiputri** [comment]
The sqlite branch is updated to address this issue, a simple conditional check using FLASK_ENV environment.
