### ISSUE TITLE
Better survey form on pedagogy app

### ISSUE THREAD

**Issue by onlyphantom** [onlyphantom/pedagogy#6]
Current survey form:
![image](https://user-images.githubusercontent.com/16984453/52074606-d8081b00-25bc-11e9-9b63-7b82652594ae.png)

The form can use some UI enhancements. Some key UI considerations:

1. Clear reminder that 1 points to poor satisfaction and 5 great satisfaction. From the current UI it's not immediately obvious or clear whether 1 or 5 should be awarded.

2. Some of the "area" could use more elaboration. Maybe explain what "training objectives were met" means, to give a better context of what a score of 5 should entail for example

3. More modern textarea, buttons, sliders etc

4. Some simple re-wording for grammatical consistency

5. A thank-you note at the end of the form, to make them feel like their feedback is important and integral to our performance management process

**Comment by ardhitoutomo** [comment]
Is it possible to close the survey after certain amount of time after the class is dismissed? Or is it meant to be always accessible all the time? Just found out that I can still access (probably almost) all the workshop by changing the last number in [survey url](http://pedagogy.azurewebsites.net/survey/130)

**Comment by onlyphantom** [comment]
Great feedback. Tiara has an idea regarding this, which is to set a page to expire or render the submit button inactive after its past due. So workshop on 15th March cannot receive further survey after 15 March for example. 

Another idea is to lock is by number of participants - so once a workshop that has 24 participants has received 24, it no longer accept additional survey.

Can you raise a separate issue on this feature request specifically?

**Comment by ardhitoutomo** [comment]
Sure. I thought this one is like more of a survey enhancement than an error so I ask here

**Comment by onlyphantom** [comment]
The new version (not committed yet) incorporating the key points above:
![image](https://user-images.githubusercontent.com/16984453/52104946-3e258a00-261f-11e9-8b05-fcd7e287a580.png)
