### ISSUE TITLE
Monthly Total of Workshop Hours

### ISSUE THREAD

**Issue by ardhitoutomo** [onlyphantom/pedagogy#7]
![image](https://user-images.githubusercontent.com/40533325/52084105-df86ee80-25d3-11e9-9981-337957359393.png)
![image](https://user-images.githubusercontent.com/40533325/52084205-1826c800-25d4-11e9-8cd5-ca85f252e788.png)
I found that both of these plots don't display the total of workshop hour explicitly. It won't be a hassle for me now but later when someone has some workshops done in all three categories in a month, I think specifying the total hour of workshop would be very nice (the information provided now is only the total of each category in a month)

**Comment by onlyphantom** [comment]
The title doesn't need to include the square bracket tag - we can use the "Labels" feature on GitHub instead to tag issues by categories: bugs, feature request, enhancement etc

**Comment by ardhitoutomo** [comment]
> The title doesn't need to include the square bracket tag - we can use the "Labels" feature on GitHub instead to tag issues by categories: bugs, feature request, enhancement etc

I can't do that because I can't select the issue and change the label. I think github doesn't allow me to do that in your repo's issue so that's why I added the square bracket tag. Thank you for changing that for me!
